update to v1 api

diff --git a/02-tekton-basics/04-task-step-with-script.yaml b/02-tekton-basics/04-task-step-with-script.yaml
--- a/02-tekton-basics/04-task-step-with-script.yaml
+++ b/02-tekton-basics/04-task-step-with-script.yaml
@@ -1,15 +1,16 @@
-apiVersion: tekton.dev/v1beta1
+apiVersion: tekton.dev/v1
 kind: Task
 metadata:
   name: script
 spec:
   steps:
     - name: step-with-script
-      image: alpine:3.15
+      image: alpine:3.20
       script: |
         #!/bin/sh
         echo "Step with Script..."
+        sed -i "s@https://dl-cdn.alpinelinux.org/@https://mirrors.huaweicloud.com/@g" /etc/apk/repositories
         echo "Installing necessary tooling"
-        apk add curl
-        curl -s www.magedu.com && echo "Success" || echo "Fail" 
+        apk update && apk add curl
+        curl -s www.magedu.com &> /dev/null && echo "Success" || echo "Fail" 
         echo "All done!"
